### ISSUE TITLE
Resource Uri null exception

### ISSUE THREAD

**Issue by zijam** [dart-lang/resource#17]
I'm running Dart **1.20.1** on OSX **10.12.1** with Resource package version **2.0.2**

When I try to load a resource file from my project using this code
```
  _loadConfig() async {
    var resource = new Resource("package:res/config/dev/msp_config.ini");
    mspConfig = new Config.fromString(await resource.readAsString());
  }
```
 Then I get following exception
```
Unhandled exception:
The null object does not have a getter 'scheme'.

NoSuchMethodError: method not found: 'scheme'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      readAsString.<readAsString_async_body> (package:resource/src/io_io.dart:53:11)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

I have the file in my project folder
![screen shot 2016-11-21 at 11 09 50](https://cloud.githubusercontent.com/assets/695088/20478703/76bd30dc-afdb-11e6-9589-ce33ae400b59.png)

It looks like the external isolate call in **resolve.dart** file return null  

```
/// Helper function for resolving to a non-relative, non-package URI.
Future<Uri> resolveUri(Uri uri) async {
  if (uri.scheme == "package") {
    return Isolate.resolvePackageUri(uri);
  }
  return Uri.base.resolveUri(uri);
}
```

**Comment by thosakwe** [comment]
Having this error too, running same Dart version, same resource version, and OSX Sierra

**Comment by lrhn** [comment]
Good point. Yes, if the resolvePackageUri  call returns `null`, then the package isn't available. The error message should be better for that case.
